// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: ItemComponentBrand.proto

package inventory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ItemComponentBrandService_Store_FullMethodName         = "/inventory.ItemComponentBrandService/Store"
	ItemComponentBrandService_RollbackStore_FullMethodName = "/inventory.ItemComponentBrandService/RollbackStore"
)

// ItemComponentBrandServiceClient is the client API for ItemComponentBrandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ItemComponentBrandServiceClient interface {
	Store(ctx context.Context, in *ItemComponentBrandRequest, opts ...grpc.CallOption) (*Response, error)
	RollbackStore(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*Response, error)
}

type itemComponentBrandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemComponentBrandServiceClient(cc grpc.ClientConnInterface) ItemComponentBrandServiceClient {
	return &itemComponentBrandServiceClient{cc}
}

func (c *itemComponentBrandServiceClient) Store(ctx context.Context, in *ItemComponentBrandRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, ItemComponentBrandService_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemComponentBrandServiceClient) RollbackStore(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, ItemComponentBrandService_RollbackStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemComponentBrandServiceServer is the server API for ItemComponentBrandService service.
// All implementations must embed UnimplementedItemComponentBrandServiceServer
// for forward compatibility.
type ItemComponentBrandServiceServer interface {
	Store(context.Context, *ItemComponentBrandRequest) (*Response, error)
	RollbackStore(context.Context, *RollbackRequest) (*Response, error)
	mustEmbedUnimplementedItemComponentBrandServiceServer()
}

// UnimplementedItemComponentBrandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItemComponentBrandServiceServer struct{}

func (UnimplementedItemComponentBrandServiceServer) Store(context.Context, *ItemComponentBrandRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedItemComponentBrandServiceServer) RollbackStore(context.Context, *RollbackRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackStore not implemented")
}
func (UnimplementedItemComponentBrandServiceServer) mustEmbedUnimplementedItemComponentBrandServiceServer() {
}
func (UnimplementedItemComponentBrandServiceServer) testEmbeddedByValue() {}

// UnsafeItemComponentBrandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemComponentBrandServiceServer will
// result in compilation errors.
type UnsafeItemComponentBrandServiceServer interface {
	mustEmbedUnimplementedItemComponentBrandServiceServer()
}

func RegisterItemComponentBrandServiceServer(s grpc.ServiceRegistrar, srv ItemComponentBrandServiceServer) {
	// If the following call pancis, it indicates UnimplementedItemComponentBrandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItemComponentBrandService_ServiceDesc, srv)
}

func _ItemComponentBrandService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemComponentBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemComponentBrandServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemComponentBrandService_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemComponentBrandServiceServer).Store(ctx, req.(*ItemComponentBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemComponentBrandService_RollbackStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemComponentBrandServiceServer).RollbackStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemComponentBrandService_RollbackStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemComponentBrandServiceServer).RollbackStore(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemComponentBrandService_ServiceDesc is the grpc.ServiceDesc for ItemComponentBrandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemComponentBrandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.ItemComponentBrandService",
	HandlerType: (*ItemComponentBrandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _ItemComponentBrandService_Store_Handler,
		},
		{
			MethodName: "RollbackStore",
			Handler:    _ItemComponentBrandService_RollbackStore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ItemComponentBrand.proto",
}
