// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: SettingItemBrand.proto

package inventory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SettingItemBrandService_Store_FullMethodName         = "/inventory.SettingItemBrandService/Store"
	SettingItemBrandService_RollbackStore_FullMethodName = "/inventory.SettingItemBrandService/RollbackStore"
)

// SettingItemBrandServiceClient is the client API for SettingItemBrandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettingItemBrandServiceClient interface {
	Store(ctx context.Context, in *SettingItemBrandRequest, opts ...grpc.CallOption) (*Response, error)
	RollbackStore(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*Response, error)
}

type settingItemBrandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSettingItemBrandServiceClient(cc grpc.ClientConnInterface) SettingItemBrandServiceClient {
	return &settingItemBrandServiceClient{cc}
}

func (c *settingItemBrandServiceClient) Store(ctx context.Context, in *SettingItemBrandRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, SettingItemBrandService_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingItemBrandServiceClient) RollbackStore(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, SettingItemBrandService_RollbackStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingItemBrandServiceServer is the server API for SettingItemBrandService service.
// All implementations must embed UnimplementedSettingItemBrandServiceServer
// for forward compatibility.
type SettingItemBrandServiceServer interface {
	Store(context.Context, *SettingItemBrandRequest) (*Response, error)
	RollbackStore(context.Context, *RollbackRequest) (*Response, error)
	mustEmbedUnimplementedSettingItemBrandServiceServer()
}

// UnimplementedSettingItemBrandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettingItemBrandServiceServer struct{}

func (UnimplementedSettingItemBrandServiceServer) Store(context.Context, *SettingItemBrandRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedSettingItemBrandServiceServer) RollbackStore(context.Context, *RollbackRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackStore not implemented")
}
func (UnimplementedSettingItemBrandServiceServer) mustEmbedUnimplementedSettingItemBrandServiceServer() {
}
func (UnimplementedSettingItemBrandServiceServer) testEmbeddedByValue() {}

// UnsafeSettingItemBrandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettingItemBrandServiceServer will
// result in compilation errors.
type UnsafeSettingItemBrandServiceServer interface {
	mustEmbedUnimplementedSettingItemBrandServiceServer()
}

func RegisterSettingItemBrandServiceServer(s grpc.ServiceRegistrar, srv SettingItemBrandServiceServer) {
	// If the following call pancis, it indicates UnimplementedSettingItemBrandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SettingItemBrandService_ServiceDesc, srv)
}

func _SettingItemBrandService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingItemBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingItemBrandServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingItemBrandService_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingItemBrandServiceServer).Store(ctx, req.(*SettingItemBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingItemBrandService_RollbackStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingItemBrandServiceServer).RollbackStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingItemBrandService_RollbackStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingItemBrandServiceServer).RollbackStore(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SettingItemBrandService_ServiceDesc is the grpc.ServiceDesc for SettingItemBrandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettingItemBrandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.SettingItemBrandService",
	HandlerType: (*SettingItemBrandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _SettingItemBrandService_Store_Handler,
		},
		{
			MethodName: "RollbackStore",
			Handler:    _SettingItemBrandService_RollbackStore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "SettingItemBrand.proto",
}
